#!/usr/bin/env bash
# Display "Bad luck" for the 4th loop iteration
# Display "Good luck" for the 8th loop iteration 
# Display "Best School" for the other iterations

count=0

while [ $count -lt 10 ]
do 

	if [ $count -eq 3 ]
	then 
	echo "bad luck"
	elif [ $count -eq 7 ]
	then 
	 echo "good luck"
	else 
	echo "best school"
	fi 
	(( count++ ))
