#!/usr/bin/env bash
# Display number 1 to 20 in addition to:
#  "bad luck from China for the 4th loop iteration
#  "bad luck from japan" luck from Japan for the 9th loop iteration
#  "bad luck from ital" for the 17th loop iteration

count=0

while [ $count -le 20 ]
do 
	echo "$count"
	case $count in 
	"4") echo "bad luck from China";;
	"9") echo "bad luck from Japan";;
	"17") echo "bad luck from Italy";;
	esac
	(( count++ ))
